name: yt-video-hosted

on:
  push:
    branches:
    - main  # Or 'master', depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Node.js (or any other environment you use for building)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Replace with the version you need

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the project
    - name: Build the project
      run: npm run build  # Assumes `npm run build` is the correct build command

    # Step 5: Sync the build to S3
    - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: ./build  # Adjust this if your build output is elsewhere
